### [사장님] 회원 가입을 합니다.
POST {{host_api}}/api/v1/boss/sign-up
Content-Type: application/json

{
    "name": "토키토",
    "accountNumber": "1002222222222",
    "phoneNumber": "01023456789",
    "nickName": "토토토",
    "email": "gochi97@naver.com",
    "profileUrl": "s3.www.www"

}
