### 회원가입을 합니다.
POST {{host_api}}/api/v1/sign-up
Content-Type: application/json

{
    "name": "고토끼",
    "nickName": "토끼3",
    "email": "starpaks7@gmail.com",
    "pictureUrl": "tokki.jpg"
}

> {%
client.global.set("SESSION", response.body["data"])
%}


### 회원을 탈퇴합니다.
PUT {{host_api}}/api/v1/sign-out
Content-Type: application/json
Authorization: Bearer {{SESSION}}


### 회원 정보 조회
GET {{host_api}}/api/v1/my-page
Content-Type: application/json
Authorization: Bearer {{SESSION}}

### 사장님 등록하기
POST  {{host_api}}/api/v1/bossInfo
Content-Type: application/json
Authorization: Bearer {{SESSION}}


{
    "bossName": "토끼",
    "bossPhoneNumber": "01023452344"
}



