### 회원가입을 합니다.
POST {{host_api}}/api/v1/sign-up
Content-Type: application/json

{
    "name": "고토끼",
    "nickName": "토끼",
    "email": "tokki@streetVendor.com",
    "pictureUrl": "tokki.jpg"
}

> {%
client.global.set("SESSION", response.body["data"])
%}


### 회원을 탈퇴합니다.
PUT {{host_api}}/api/v1/sign-out
Content-Type: application/json
Authorization: Bearer {{SESSION}}


