> {%
client.global.set("SESSION", response.body["data"])
%}

### 문의사항을 등록한다.
POST {{host_api}}/api/v1/question
Content-Type: application/json
Authorization: Bearer {{SESSION}}

{
    "type": "OTHERS",
    "title": "환불이 안돼요ㅠㅠ",
    "content": "돈이 언제 들어올까요?",
    "images": []
}

### 나의 문의사항을 조회한다
GET {{host_api}}/api/v1/question
Content-Type: application/json
Authorization: Bearer {{SESSION}}
