### 새로운 가게를 등록합니다.
POST {{host_api}}/api/v1/store
Content-Type: application/json
Authorization: Bearer {{SESSION}}

{
    "name": "토끼의 붕어빵 창업",
    "pictureUrl": "https://store.com",
    "location": {
      "latitude": 14.23232,
      "longitude": 30.2323
    },
    "description": "가게 설명",
    "category": "BUNG_EO_PPANG",
    "menus": [
        {
            "pictureUrl": "https://menu.com",
            "name": "팥 붕어빵",
            "price": "2000",
            "amount": 2
        },
        {
            "pictureUrl": "https://menu.com",
            "name": "슈크림",
            "price": "2000",
            "amount": 5
        }
    ],
    "paymentMethods": [
        "CASH",
        "ACCOUNT_TRANSFER"
    ],
    "businessHours": [
        {
            "startTime": "08:00",
            "endTime": "08:01",
            "days": "MON"
        }
    ]
}


### 나의 가게 목록을 조회합니다.
GET {{host_api}}/api/v1/my-stores
Authorization: Bearer {{SESSION}}
