### [사장님] 회원 가입을 합니다.
POST {{host_api}}/boss/v1/sign-up
Content-Type: application/json

{
    "name": "고토끼",
    "accountNumber": "1002222222222",
    "phoneNumber": "01023456789",
    "nickName": "토끼천재",
    "email": "tokki2@naver.com",
    "profileUrl": "s3.www.www"

}

> {%
client.global.set("SESSION", response.body["data"])
 %}




