### [사장님] 회원 가입을 합니다.
POST {{host_api}}/boss/v1/sign-up
Content-Type: application/json

{
    "name": "고잼민",
    "accountNumber": "1002222222222",
    "phoneNumber": "01023456789",
    "nickName": "잼민이2",
    "email": "woalswhwh2@naver.com",
    "profileUrl": "s3.www.www"

}

> {%
client.global.set("SESSION", response.body["data"])
 %}




### 새로운 가게를 등록합니다.
POST {{host_api}}/boss/v1/create-store
Content-Type: application/json
Authorization: Bearer {{SESSION}}

{

    "name": "잼민이네 근처 가게",
    "pictureUrl": "https://store.com",
    "location": {
        "latitude": 37.45064589999995,
        "longitude": 126.71990259999977
    },
    "description": "가게 설명",
    "category": "BUNG_EO_PPANG",
    "menus": [
        {
            "pictureUrl": "https://menu.com",
            "name": "팥 붕어빵",
            "price": 2000,
            "menuCount": 2
        },
        {
            "pictureUrl": "https://menu.com",
            "name": "슈크림",
            "price": 2000,
            "menuCount": 5
        }
    ],
    "paymentMethods": [
        "ACCOUNT_TRANSFER"
    ],
    "businessHours": [
        {
            "startTime": "08:00",
            "endTime": "08:01",
            "days": "MON"
        },
        {
            "startTime": "21:00",
            "endTime": "23:00",
            "days": "TUE"
        },
        {
            "startTime": "00:00",
            "endTime": "04:00",
            "days": "WED"
        }
    ],
    "storeImages": [
        {
            "isThumbNail": true,
            "imageUrl": "http:/wefwef"
        }
    ]
}

